### ISSUE TITLE
Different result with linter in local

### ISSUE THREAD

**Issue by airween** [coreruleset/coreruleset#4058]
### Describe the bug

CRS workflow has a [linter test](https://github.com/coreruleset/coreruleset/blob/main/.github/workflows/lint.yaml#L94-L99) which does several checks. I downloaded [crs-linter](https://github.com/coreruleset/crs-linter/) and the last CRS version, and run that test.

I get this error:
```
::group ::../../coreruleset_tmp2/rules/REQUEST-901-INITIALIZATION.conf
::error title=unset TX variable,file=../../coreruleset_tmp2/rules/REQUEST-901-INITIALIZATION.conf,line=333,endLine=333::TX variable 'ENABLE_DEFAULT_COLLECTIONS' not set / later set (VAR)
```
and the exit code of the linter is 1.

I checked this `TX` variable, and the linter result is correct: `TX:ENABLE_DEFAULT_COLLECTIONS` is never set before we reference that.

But the last PR's check (and the other ones) finished successfully, see [this one](https://github.com/coreruleset/coreruleset/actions/runs/14129638721/job/39586497469#step:8:32) for example.

### Steps to reproduce

```
mkdir lintercheck
cd lintercheck

git clone https://github.com/coreruleset/crs-linter.git crs-linter
Cloning into '.'...
remote: Enumerating objects: 380, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 380 (delta 11), reused 13 (delta 5), pack-reused 344 (from 2)
Receiving objects: 100% (380/380), 156.55 KiB | 3.40 MiB/s, done.
Resolving deltas: 100% (172/172), done.

git clone https://github.com/coreruleset/coreruleset coreruleset
Cloning into 'coreruleset'...
remote: Enumerating objects: 34999, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 34999 (delta 42), reused 20 (delta 18), pack-reused 34938 (from 4)
Receiving objects: 100% (34999/34999), 10.00 MiB | 29.01 MiB/s, done.
Resolving deltas: 100% (27690/27690), done.

crs_linter/cli.py --output=github -r ../../coreruleset/crs-setup.conf.example -r '../../coreruleset/rules/*.conf' -t ../APPROVED_TAGS -v "4.13.0-dev"
::group ::../../coreruleset/crs-setup.conf.example
::endgroup::
::group ::../../coreruleset/rules/REQUEST-901-INITIALIZATION.conf
::error title=unset TX variable,file=../../coreruleset/rules/REQUEST-901-INITIALIZATION.conf,line=333,endLine=333::TX variable 'ENABLE_DEFAULT_COLLECTIONS' not set / later set (VAR)
::endgroup::
...

echo $?
1
```

### Expected behaviour

I think CI workflow should show this result.

### Actual behaviour

See the mentioned [output](https://github.com/coreruleset/coreruleset/actions/runs/14129638721/job/39586497469#step:8:128)

### Additional context

N/A

### Your Environment

* CRS version (e.g., v3.2.0): 4.13.0-dev
* Paranoia level setting: -
* ModSecurity version (e.g., 2.9.3): not relevant
* Web Server and version (e.g., apache 2.4.41): not relevant
* Operating System and version: not relevant

**Comment by airween** [comment]
Could anyone check and confirm this behavior?

**Comment by Xhoenix** [comment]
@airween I checked and was able to reproduce the same result as yours. You're right, the `TX:ENABLE_DEFAULT_COLLECTIONS` is disabled in `crs-setup.conf.example`, as such the variable is not initialized, and crs-linter's output is correct.

```
(.venv) ┌──(jit🏠LAPTOP)-[~/coreruleset]
└─$ crs-linter --output=github -t util/APPROVED_TAGS -r ./crs-setup.conf.example  -r "./rules/*.conf" -v "4.13.0-dev"
::group ::./crs-setup.conf.example
::endgroup::
::group ::./rules/REQUEST-901-INITIALIZATION.conf
::error title=unset TX variable,file=./rules/REQUEST-901-INITIALIZATION.conf,line=333,endLine=333::TX variable 'ENABLE_DEFAULT_COLLECTIONS' not set / later set (VAR)
::endgroup::
```

**Comment by theseion** [comment]
Opend a PR for debugging: #4060

**Comment by theseion** [comment]
The PyPi package contains the old script from the repository, _not_ the current 0.1.0 release from the `crs-linter` repo. It's probably best to create a new release in the GitHub repo and then a new version of the PyPi package.

**Comment by theseion** [comment]
@airween Still not entirely sure, what's going on. However, I noticed that logging is broken. I've opened a PR. I propose we merge that, publish a new version to PyPi and then we can enable debug logging in the CRS pipeline.

**Comment by fzipi** [comment]
Done. Created https://github.com/coreruleset/crs-linter/releases/tag/v0.1.1

**Comment by theseion** [comment]
Here's the debug output for v0.0.1: https://github.com/coreruleset/coreruleset/actions/runs/14165231938/job/39677175434?pr=4067. I still don't understand why it's not detecting the variable, but at least we can now see something.

**Comment by Xhoenix** [comment]
Figured out the problem. It has to do with the path for the rules:

https://github.com/coreruleset/coreruleset/blob/336a58fe6db6999b2d79f0c35938a5d55c71b160/.github/workflows/lint.yaml#L97

Changing the path to an absolute one, or a relative one like, `-r './rules/*.conf' \` produces the error as it should.

**Comment by airween** [comment]
> Changing the path to an absolute one, or a relative one like, `-r './rules/*.conf' \` or `-r "$PWD/rules/*.conf" \` produces the error as it should.

I checked and confirmed this. I'm going to investigate the root cause soon.

**Comment by theseion** [comment]
This is fixed, right?

**Comment by airween** [comment]
Yes, definitely. Closing this one.
